[package]
name = "ripasso"
version = "0.2.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com", "Alexander Kjäll <alexander.kjall@gmail.com>"]
license-file = "LICENCE"

[dependencies]
notify = "4"
glob = "0.2"
gpgme = "0.8"
chrono = "0.4"
git2 = "0.10.0"
log = "0.4.5"
env_logger = "0.6"
dirs = "1.0"
rand = "0.7"
xkcd-password = "0.1.1"
whoami = "0.5.3"

[dev-dependencies]
tempdir = "0.3"
tempfile = "3.1.0"

[workspace]

members = [
    "gtk", "qml", "cursive", "man"
]
