[package]
name = "ripasso"
description = "A password manager that uses the file format of the standard unix password manager 'pass'"
repository = "https://github.com/cortex/ripasso/"
keywords = ["password-manager", "pass"]
version = "0.3.0"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com", "Alexander Kjäll <alexander.kjall@gmail.com>"]
license = "GPL-3.0-only"
license-file = "LICENCE"
edition = '2018'

[dependencies]
notify = "4"
glob = "0.3.0"
gpgme = "0.9.1"
chrono = "0.4"
git2 = "0.10.2"
log = "0.4.8"
env_logger = "0.7.0"
dirs = "2.0.2"
rand = "0.7.2"
xkcd-password = "0.1.1"
whoami = "0.5.3"

[dev-dependencies]
tempdir = "0.3"
tempfile = "3.1.0"

[workspace]

members = [
    "gtk", "qml", "cursive", "man"
]
