[package]
name = "ripasso-cursive"
version = "0.2.0"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>", "Alexander Kjäll <alexander.kjall@gmail.com>"]

[dependencies]
cursive = "0.12"
clipboard = "0.5"
ripasso = { path = "../"}
env_logger = "0.6"
