[package]
name = "ripasso-cursive"
description = "A password manager that uses the file format of the standard unix password manager 'pass', this is the ncurses frontend application"
repository = "https://github.com/cortex/ripasso/"
keywords = ["password-manager", "pass"]
version = "0.4.0"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>", "Alexander Kjäll <alexander.kjall@gmail.com>"]
license = "GPL-3.0-only"
edition = '2018'
build = "build.rs"

[dependencies]
cursive = { version = "0.14", features = ["toml"]}
clipboard = "0.5"
ripasso = { path = "../", version = "0.4.0" }
env_logger = "0.7.1"
locale_config = "0.3.0"
unic-langid = "0.7.1"
gettext = "0.4.0"
lazy_static = "1.4.0"

[build-dependencies]
glob = "0.3.0"
