[package]
name = "ripasso-cursive"
version = "0.3.0"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>", "Alexander Kjäll <alexander.kjall@gmail.com>"]
edition = '2018'

[dependencies]
cursive = "0.12"
clipboard = "0.5"
ripasso = { path = "../"}
env_logger = "0.6"
git2 = "0.10.2"
